#!/usr/bin/with-contenv bash

pd_basic_opts="
-c /config/
--cache-file=/config/cache.bolt
--uid=${PUID:-911}
--gid=${PGID:-911}
--umask=0100775
-o allow_other
"

IFS=" " read -r -a pd_user_opts <<< "$PLEXDRIVE_OPTS"

mount_command="plexdrive mount /cloud-encrypted $(echo $pd_basic_opts) ${pd_user_opts[@]}"
echo "executing => $mount_command"
exec s6-setuidgid abc $mount_command
