#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config /cache /log /cloud /data /local /data-decrypted /local-decrypted

# permissions
chown -R abc:abc /config /cache /log /cloud /data /data-decrypted /local-decrypted
chmod a+x /usr/bin/plexdrive_setup
