#!/usr/bin/with-contenv bash

# make folders
mkdir -p /cloud-encrypted /cloud-decrypted /local-decrypted

# change permissions
chown -R abc:abc /config /cloud-encrypted /cloud-decrypted /local-encrypted /local-decrypted /unionfs

chmod a+x /usr/bin/plexdrive_setup
