#!/usr/bin/with-contenv bash

echo "*** checking config"
while [ ! -f "/config/config.json" ] || [ ! -f "/config/token.json" ]; do
	echo "Waiting for config files in /config. Retrying in 30s ..."
	echo "RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup"
	sleep 30
done

echo "*** checking mountpoint"
while [ $(findmnt /cloud-encrypted | grep fuse | wc -l) != "0" ]; do
	echo "mountpoint (/cloud-encrypted) already mounted. Retrying in 15s ..."
	sleep 15
done

# display version
echo "*** plexdrive $(plexdrive --version) ready!"
